add check for firebase secret in android app distribution workflow

diff --git a/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yaml b/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yaml
--- a/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yaml
+++ b/.github/workflows/android_fastlane_firebase_app_distribution_workflow.yaml
@@ -31,7 +31,16 @@ jobs:
           EOF
       - name: Flutter pub get
         run: flutter pub get
-
+      - name: Check Firebase Secret
+        env:
+          FIREBASE_CLI_TOKEN: ${{ secrets.FIRBASE_CLI_TOKEN }}
+        run: |
+          if [ -z "$FIREBASE_CLI_TOKEN" ]; then
+            echo "Secret not found"
+            exit 1
+          else
+            echo "Secret found"
+          fi
       - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
